### ISSUE TITLE
Module Tests and WebGL

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1375]
### Please describe the problem (or idea)
- [x] The tests for the following modules fail: (#1376)
1. Colorbar
2. Draw Rectangle
3. Gamma Correction
4. Paint Bucket
5. Replace Color
6. Rotate
7. Tint
These tests fail either because the modules are updated or otherwise. These need to be fixed.

- [x] The following Modules are not tested: (#1377)
1. Import Image

- [x] The following modules are not benchmarked because they need WebGL but do not use puppeteer: (#1378)
1. Text Overlay
2. Blob Analysis

The above three issues can be split into three dedicated issues.

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by keshav234156** [comment]
cc-@jywarren

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers

**Comment by keshav234156** [comment]
@HarshKhandeparkar For 7 modules we need to change the benchmarks .I am working on it

**Comment by HarshKhandeparkar** [comment]
Which 7?

**Comment by HarshKhandeparkar** [comment]
The 7 require test fixes, not benchmarks
