### ISSUE TITLE
Checklist and coordination for v3.7.0 minor release

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#1751]
Just getting started... no rush on this, but noting we will be basing this out of the project, not the milestone. cc @publiclab/is-maintainers (@HarshKhandeparkar does this notify sub-teams?)

This template guides us through the steps of creating a new release, based on [conversation and testing in https://github.com/publiclab/image-sequencer/issues/1692.

Discuss with @publiclab/is-maintainers if anything is ambiguous!

* [x] open an issue using the "release" template with this checklist with title `Checklist and coordination for v3.7.0 minor release` (see [semantic versioning](https://docs.npmjs.com/about-semantic-versioning/))
* [x] compile release notes below from corresponding [release project](https://github.com/publiclab/image-sequencer/projects/4)
* [x] update version number in `examples/sw.js` (ex #1734) and `package.json` (ex #1695)
* [x] finalize and merge to `main` branch (freeze merges to `main` branch until next step)

Checklist moved to https://github.com/publiclab/image-sequencer/pull/2036

* [ ] merge, build and publish `/dist/` files to `stable` (merges to `main` branch can resume for next release)
* [ ] create a release on GitHub and use features description + release notes from below
* [ ] tag version number branch (i.e. `v3.7.0`)
* [ ] publish tagged branch to `npm`
* [ ] publish to live `github-pages` demo (with [bash script](https://github.com/publiclab/image-sequencer/pull/1703) from `/scripts/update_demo`) (from within GitPod works well)
* [ ] move anything necessary to next release project, i.e. https://github.com/publiclab/image-sequencer/projects/4
* [ ] close this issue!
****

#### Added

- New Shadow Module: Add shadows (borders) to images in bulk! https://github.com/publiclab/image-sequencer/pull/1507 by @niravasher 
- New Alpha masking module: https://github.com/publiclab/image-sequencer/pull/1546 by @blurry-x-face 
- New sharpness module in #1612 by @waridrox

#### Fixed

- compiled /dist/ files from `v3.7.0`
- Percentage Parsing: Percentage values passed to the sequencer are now parsed more consistently. (https://github.com/publiclab/image-sequencer/pull/1733)
- Safari Fix: Image Sequencer will now work in the Safari browser! (https://github.com/publiclab/image-sequencer/pull/1740)
- offline caching improvements in https://github.com/publiclab/image-sequencer/pull/1819 and -https://github.com/publiclab/image-sequencer/pull/1807 by @vivek-30
- variety of other bugfixes!
-  fixed Module selector console error #1543 by @ss62171

#### Changed

- switch to GitHub Actions in https://github.com/publiclab/image-sequencer/pull/1783 (team effort!)
- switch to `expr-eval` in https://github.com/publiclab/image-sequencer/pull/1729 by @jywarren
- CLI improvements in https://github.com/publiclab/image-sequencer/pull/1785 by @blurry-x-face 
- dependencies updated
- yarn.lock removed #2035

**Comment by HarshKhandeparkar** [comment]
I think it does notify sub-teams.
I will move the milestone items to 3.6.1 as of now. We can then rename it if needed.

**Comment by HarshKhandeparkar** [comment]
Done.

**Comment by jywarren** [comment]
Added a couple bugfixes for range step size for floats in https://github.com/publiclab/image-sequencer/pull/1777 and https://github.com/publiclab/image-sequencer/pull/1776 to the project for 3.7.0!

**Comment by HarshKhandeparkar** [comment]
After considering the changes made, I renamed everything to 3.7.0.

**Comment by HarshKhandeparkar** [comment]
Also wrote part of the release notes.

**Comment by jywarren** [comment]
I added these:

* new sharpness module in #1612
* switch to GitHub Actions in https://github.com/publiclab/image-sequencer/pull/1783
* offline caching improvements in https://github.com/publiclab/image-sequencer/pull/1819 and https://github.com/publiclab/image-sequencer/pull/1807
* switch to `expr-eval` in https://github.com/publiclab/image-sequencer/pull/1729
* CLI improvements in https://github.com/publiclab/image-sequencer/pull/1785

**Comment by harshkhandeparkar** [comment]
> I added these:
> 
> * new sharpness module in [Module for sharpening images #1612](https://github.com/publiclab/image-sequencer/issues/1612)
> * switch to GitHub Actions in [try moving to Github Actions from Travis for CI #1783](https://github.com/publiclab/image-sequencer/pull/1783)
> * offline caching improvements in [Offline caching: Try To fetch latest data first then shift to cached one. #1819](https://github.com/publiclab/image-sequencer/pull/1819) and [fixed registration problem of service worker #1807](https://github.com/publiclab/image-sequencer/pull/1807)
> * switch to `expr-eval` in [switch to expr-eval for dynamic module #1729](https://github.com/publiclab/image-sequencer/pull/1729)
> * CLI improvements in [refactor cli code #1785](https://github.com/publiclab/image-sequencer/pull/1785)

Added them to the v3.7.0 project :)

**Comment by harshkhandeparkar** [comment]
I just marked some PRs that are almost done but need some more work (such as tests) with the `incomplete` label. Some others that required a lot more work were converted to drafts.

**Comment by harshkhandeparkar** [comment]
Added a few more issues to the project, including this one which is ready to merge: https://github.com/publiclab/image-sequencer/pull/1543

**Comment by jywarren** [comment]
That's awesome. Thanks @harshkhandeparkar!! Maybe we should release 3.7.0 now and batch anything else into the next?

**Comment by harshkhandeparkar** [comment]
How about releasing another 3.6.x patch?

**Comment by harshkhandeparkar** [comment]
Except for the shadow and alpha masking modules, all other PRs are bug fixes or refactorings.

**Comment by jywarren** [comment]
Well, if we even have 2 new things, it qualifies for a minor version bump, no? Are you OK with 3.7.0? Or are you worried about the project needing to be reorganized as a result?

**Comment by harshkhandeparkar** [comment]
> Well, if we even have 2 new things, it qualifies for a minor version bump, no?
Yeah true, let's make it 3.7.0.

> Or are you worried about the project needing to be reorganized as a result?
Not at all :)

But I was looking at potentially merging https://github.com/publiclab/image-sequencer/pull/1673 because it adds just a single character.

**Comment by jywarren** [comment]
OK, so this may need to be published due to errors related to https://github.blog/2021-09-01-improving-git-protocol-security-github/ ; I'd prefer to do it as 3.6.x as a bugfix on the stable branch, so I may do that first, but then we might as well roll out a new version with all these fixes anyways. 

Short story: the package.json link to git://github.com/jywarren/imgareaselect.git needs to change to https:// as it's breaking downstream repos like https://github.com/publiclab/plots2/

**Comment by jywarren** [comment]
Gah, unfortunately forgot to follow the checklist entirely before releasing v3.7.0, so it doesn't include the latest /dist/ builds! Doh! :sob:

Working on it now but it looks like we have a yarn.lock conflict. Need to review again why we track yarn.lock.

Also, to add to the process:

1. if it doesn't merge cleanly into stable, do we force push to stable? or rebase a copy of main? Or did we do something wrong resulting in stable not getting merged to cleanly?
2. let's be sure to copy the whole checklist into the PR, so we follow it there.
3. specify node version to work with when publishing

**Comment by jywarren** [comment]
So let's also do:

* [ ] add to [checklist](https://github.com/publiclab/image-sequencer/blob/main/.github/ISSUE_TEMPLATE/release_workflow.md) a step for copying checklist over to the PR
* [ ] add clarification about rebasing vs. force pushing? Check what we've done in the past. Will force pushing or rebasing affect the auto-build steps for https://beta.sequencer.publiclab.org?
* [ ] add node version (16) and possibly platform to use when compiling?

~Maybe move the pull request template to `PULL_REQUEST_TEMPLATE` and add `?template=` to some URL to make copying over faster? No, that won't work because we want the checklist to be partially completed, and to be copying over the release notes too.~

**Comment by jywarren** [comment]
To clarify on rebase vs. force - `v3.6.0` was a2d654321d79ce8773c5621e3b4aa8f371d669e2, which is identical in both `main` and `stable` branches. So we aren't rebasing, as far as I can see. 

I don't see previous evidence of compiling to /dist/ in the stable commit history, and searched back several versions. So I believe we are force-pushing to stable, then compiling in a follow-up commit. I think we talked through this process carefully in #1692 or elsewhere but just confirming here; process is:

- [ ] force push to `stable`
- [ ] then in `stable` branch, compile `/dist/` files with `grunt build`
- [ ] add `/dist/` files with `git add -f /dist/*` and commit them to `stable` branch
- [ ] run `npm publish` (logging in first as necessary)

**Comment by jywarren** [comment]
Noting (responding to https://github.com/publiclab/image-sequencer/pull/2034#issuecomment-1010438427) running the `main` branch in gitpod (after deleting yarn.lock, although possibly unrelated) i am able to run `npm install` now. node version `16.3.0`, probably same as yesterday...

**Comment by jywarren** [comment]
https://github.com/publiclab/image-sequencer/releases/tag/v3.7.1 released! cc @publiclab/is-reviewers @publiclab/is-maintainers @publiclab/is-module-maintainers @publiclab/is-ui-maintainers @publiclab/is-cli-maintainers 🎉

**Comment by jywarren** [comment]
Moving to https://github.com/publiclab/image-sequencer/issues/2037 for any following changes! Thanks, all!
