### ISSUE TITLE
Checklist and coordination for v3.8.0 minor release

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#2089]
This template guides us through the steps of creating a new release, based on conversation and testing in [#1692](https://github.com/publiclab/image-sequencer/issues/1692).

Discuss with @publiclab/is-maintainers if anything is ambiguous!

Also see:

- https://github.com/publiclab/image-sequencer/issues/2038

* [x] open an issue using the "release" template with this checklist with title `Checklist and coordination for v0.0.0 major/minor/patch release` (see [semantic versioning](https://docs.npmjs.com/about-semantic-versioning/))
* [ ] create a release [project](https://github.com/publiclab/image-sequencer/projects) from [this template](https://github.com/publiclab/image-sequencer/projects/5). You can copy a project from its menu.
* [ ] compile release notes below from corresponding [release project](https://github.com/publiclab/image-sequencer/projects).
* [ ] open a pull request with updated version numbers
    * [ ] update version number in `package.json` (ex #1695)
    * [ ] update version number in `examples/sw.js` (ex #1734)
    * [ ] run `npm install` to update `package-lock.json` (from recent node version - 16 at time of writing, in GitPod should work)
    * [ ] check in `package-lock.json`
* [ ] finalize and merge to `main` branch (freeze merges to `main` branch until next step)

Now, move to `stable` branch:

* [ ] force push from `main` to `stable`
* [ ] then in `stable` branch, compile `/dist/` files with `grunt build`
* [ ] add `/dist/` files with `git add -f /dist/*` and commit them to `stable` branch
* [ ] publish `stable` branch to `npm` with `npm publish` (logging in first as necessary)

Draft a release:

* [ ] [create a release on GitHub](https://github.com/publiclab/image-sequencer/releases) and use features description + release notes from below
* [ ] tag version number branch (i.e. `v0.0.0`) based on `stable` or choose `stable`
* [ ] publish to live Github pages [demo](https://sequencer.publiclab.org) (with [bash script](https://github.com/publiclab/image-sequencer/pull/1703) from `/scripts/update-demo`) (from within GitPod works well)
* [ ] move anything necessary to next release project, i.e. https://github.com/publiclab/image-sequencer/projects/[insert project number]
* [ ] close this issue!

Noting we're now in this process in https://github.com/publiclab/image-sequencer/issues/1751 for `v3.7.0`.

****

### Release notes
Compile and edit release notes below, to be copied into the release description.

#### Added

- https://github.com/publiclab/image-sequencer/pull/1615 (needs test)
- https://github.com/publiclab/image-sequencer/pull/1607

#### Fixed

(almost ready):

- https://github.com/publiclab/image-sequencer/pull/1564 (high priority)
- https://github.com/publiclab/image-sequencer/pull/1625 (high priority, needs test)
- https://github.com/publiclab/image-sequencer/pull/1634
