### ISSUE TITLE
Planning Issue for the Image Sequencer GSoC Project

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#23]
This is my plan for the summer. Please suggest any suggestions which you may deem fit @jywarren @ebarry. There is still a lot to be written here, will keep adding more points with time. This is by no means, exhaustive.
[Link to my proposal](https://publiclab.org/notes/ccpandhare/03-18-2017/developing-image-sequencer-as-a-library)

# Phase 1 : Core functionality and JSON Input Support
In this phase I will build upon the core fuctions of Image Sequencer (addSteps, removeSteps, insertSteps, loadImage)
- [x] Create function addSteps which accepts data in many formats (JSON and otherwise) as described in the [development wiki](https://github.com/publiclab/image-sequencer/wiki/Development) (PR #24)
- [x] Create the system to be used for handling images : Instead of choosing Sharp or Jimp or lwip, I stuck to plain old DataURIs in custom Image objects. As the mentioned modules have huge functionalities which are not relevant to Image Sequencer. (PR #24)
- [x] Create the framework for using multiple images : Finally enables Image Sequencer to handle multiple images at once. (PR #24)
- [x] Similarly, create `removeSteps`, `insertSteps`, `loadImages` and modify `run` (PR #24)
- [x] Update Usage Instructions in `Readme.md`

# Phase 2 : Unit Tests, Modularization, Unified Input Parsing
- [x] Unit Tests for the methods `addSteps`, `removeSteps`, `insertSteps`, `run` (PR #28)
- [x] Image Based Unit Tests : Double Inversion Test, NDVI Test (PR #30)
- [x] Unified Input Parser : A Single Module to parse inputs in different formats - reduces source size and helps manage code. (PR #28)
- [x] Modularization of large functions which were earlier a part of `src/ImageSequencer.js` (PR #28)

# Phase 3 : Module Logs, custom I/O, headless testing, Chaining, replaceImage
- [x] Headless Browser Testing using the `tape-run` module. (PR #55) 
- [x] Method Chaining (PR #44, #53)
- [x] Added Invert Module (PR #30)
- [x] replaceImage Created, and along with it, [its gh-pages demo.](https://ccpandhare.github.io/image-sequencer/examples/replace) (PR #35)
- [x] Create a module log. This will store logs from various modules. Useful for debugging. (PR #37)
- [x] Allow modules to interact with the user, accept and output data apart from images. (example: data of a QR Code)

# Phase 4 : User Interface, Support external Images
- [x] Create Module Interface (PR #67 ISS #85)
- [x] Create the User Interface for node based and browser based implementations of Image Sequencer. (Across various PRs)
- [x] local image support on Browser (PR #81)
- [x] URL image support on Browser (PR #81)
- [x] URL image support on Node.JS (PR #81)

# Phase 5 : Additional New Features
- [x] Added method `.exportBinary()` to export images as binary (NodeJS) (PR #90)
- [x] Image testing using pixel-by-pixel comparison with a tolerance level (PR #89)
- [x] Describing module requirements using an `info.json` file for every module. (PR #92)
- [x] Implemented Complete demo (PR #92)
- [x] Added Basic Command Line Interface (CLI) (PR #95)
- [x] Publish demos to GH-Pages (PR #96)

# Phase 6 : Module Implementation & NPM
This phase involves implementing the various modules as mentioned in the Readme.md and my project proposal.
- [x] Publish to [NPM](https://www.npmjs.com/package/image-sequencer)
- [x] FisheyeGl (PR #61)
- [x] Crop (PR #56)
- [x] Invert
- [x] Segmented Colormap (PR #57)
- [x] QR Code Module (PR #72)

**Comment by jywarren** [comment]
Hi, this looks super -- I'd like to request some more explicit mention of
when tests will be added, and encourage adding a really clear test that
processes an NDVI image and does a diff comparison between a "before" and a
known "after" image, that we can visually confirm. I think this should be
done in the phase 1 and be clearly documented in the readme too -- this'll
be a really clear way to explain the system, and ensure its basic functions
are legible and concrete. Make sense?

**Comment by ccpandhare** [comment]
Okay, I will look into it and let you know if I face any issues.

**Comment by ccpandhare** [comment]
@jywarren Can you add the "Help Needed" label, please?

**Comment by ccpandhare** [comment]
> encourage adding a really clear test that processes an NDVI image and does a diff comparison between a "before" and a known "after" image, that we can visually confirm.

I am not sure on how this is to be done. Please help me out @jywarren

**Comment by jywarren** [comment]
Well, I think we could run a test on a test image, and visually confirm
(like you did with the saturation problem) that the output is correct. Then
document that example in the readme too to show how it works!

**Comment by ccpandhare** [comment]
Okay, Thanks! Will do that.

**Comment by jywarren** [comment]
Ok! Now let's find, on the public lab site, a clear before/after NDVI image and get ImageSequencer to reproduce it.  Ask Ned Horning or Chris Fastie!

**Comment by jywarren** [comment]
Also, can you merge to gh-pages branch so we can update the online demo?

**Comment by ccpandhare** [comment]
> Ok! Now let's find, on the public lab site, a clear before/after NDVI image and get ImageSequencer to reproduce it. Ask Ned Horning or Chris Fastie!

Can I generate one from Infragram?

**Comment by ccpandhare** [comment]
I had a quick check. The results from Image Sequencer are very different from those of Infragram

**Comment by jywarren** [comment]
OK - can you post them all in an issue, both before/after pairs? Let's work
on this!

On Fri, Jun 30, 2017 at 11:47 AM, Chinmay Pandhare <notifications@github.com

**Comment by jywarren** [comment]
Really coming along here! 

The fisheye module really starts to dig us into user interface and options setting stuff. 

Another thing we may want to add is -- can modules access information from previous modules? Say, if we had a module that produced a certain output, could we pass that information on to later modules to use? I don't know -- say, a decoded QR code, or... extracted EXIF data?

**Comment by jywarren** [comment]
For example, what if we included a QR code in an image and it generated metadata available to the sequencer modules? I'm thinking about for example a colored backdrop with a qr code which, when you photo it, runs a particular module automatically or something.

This is probably thinking too far ahead :-) let's think interface for now!

**Comment by ccpandhare** [comment]
Well that sure is a possibility, and I am sure it can be done!
But yes, UI should be implemented first :D

**Comment by ccpandhare** [comment]
> Another thing we may want to add is -- can modules access information from previous modules? Say, if we had a module that produced a certain output, could we pass that information on to later modules to use? I don't know -- say, a decoded QR code, or... extracted EXIF data?

Well yes! I think I can add this after the UI

**Comment by jywarren** [comment]
I think we can close this out now! But let's clean up the issues a bit as well. Congrats!
