### ISSUE TITLE
Various demo UI fixes - checklist

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#232]
Small but helpful list of tweaks we could break out into first-timers-only issues! (once the demo refactor is done (#214)

* [x] Disable/dim the `Save` button until step inputs have been changed
* [x] Disable/dim the `Add step` button until a module is selected
* [x] Show a `Press save to see changes` next to each step's `Save` button
* [x] Add a `download` button at the bottom, in a panel next to the `Add Step` button

**Comment by jywarren** [comment]
Here's where the Save button is made: 

https://github.com/publiclab/image-sequencer/blob/630eb773de712873d6323eb86275fadb2b802fc1/examples/lib/defaultHtmlStepUi.js#L94-L96

We can use the same kinds of selectors to modify it, add more text, change the styling -- using Bootstrap styles: 

https://getbootstrap.com/docs/3.3/css/

**Comment by tech4GT** [comment]
Breaking these up to make some first timer issues!!

**Comment by jywarren** [comment]
awesome!!!

**Comment by Mridul97** [comment]
Hello, I made changes to show 'Press save to see changes' next to each step's 'Save' button and add a 'download' button next to the 'Add Step' button. Please take a look. Pull request #325.

**Comment by tech4GT** [comment]
I think this issue is done, closing this up now!
